CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT      NOT NULL REFERENCES members(id),
    name       VARCHAR(50) NOT NULL,
    color      VARCHAR(7)  NOT NULL,
    sort_order INT         NOT NULL DEFAULT 0,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
