CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT       NOT NULL REFERENCES members(id),
    category_id BIGINT       NOT NULL REFERENCES categories(id),
    title       VARCHAR(200) NOT NULL,
    completed   BOOLEAN      NOT NULL DEFAULT FALSE,
    task_date   DATE         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_tasks_member_date ON tasks(member_id, task_date);
